---
# Example 1: Using envFrom with secretRef (ALL secret key-value pairs as env variables)
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-envfrom-secret
  namespace: default
spec:
  containers:
    - name: app-container
      image: myapp:1.0
      ports:
        - containerPort: 8080
      # This method injects ALL key-value pairs from the secret as environment variables
      envFrom:
        - secretRef:
            name: app-secret

---
# Example 2: Using env with valueFrom.secretKeyRef (SPECIFIC secret values as env variables)
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-specific-secret-env
  namespace: default
spec:
  containers:
    - name: app-container
      image: myapp:1.0
      ports:
        - containerPort: 8080
      # This method selects specific keys from the secret
      env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: name
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
        - name: APP_ENV
          value: "production"  # Plain environment variable

---
# Example 3: Using Volume Mount (Mount secrets as files in the container)
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret-volume
  namespace: default
spec:
  containers:
    - name: app-container
      image: myapp:1.0
      ports:
        - containerPort: 8080
      # Mount the secret as files in the container filesystem
      volumeMounts:
        - name: secret-volume
          mountPath: /etc/secrets
          readOnly: true
        - name: specific-secret-file
          mountPath: /etc/config
          readOnly: true
  # Define volumes that use secrets
  volumes:
    - name: secret-volume
      secret:
        secretName: app-secret
        # Each key becomes a file with its value as content
        # Files will be created at /etc/secrets/name and /etc/secrets/password
        defaultMode: 0400  # Read-only for owner
    - name: specific-secret-file
      secret:
        secretName: app-secret
        items:
          - key: password
            path: db_password.txt  # Create file at /etc/config/db_password.txt

---
# Example 4: Using Projected Volume (Multiple sources including secrets)
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-projected-volume
  namespace: default
spec:
  containers:
    - name: app-container
      image: myapp:1.0
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: projected-secrets
          mountPath: /var/run/secrets
          readOnly: true
  volumes:
    - name: projected-secrets
      projected:
        sources:
          - secret:
              name: app-secret
              items:
                - key: name
                  path: username
                - key: password
                  path: password

---
# Example 5: Using Secret for Docker Registry Authentication
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-private-registry
  namespace: default
spec:
  # This secret type is used for pulling images from private registries
  imagePullSecrets:
    - name: regcred  # This should be a secret of type kubernetes.io/dockercfg or kubernetes.io/dockerjson
  containers:
    - name: app-container
      image: myregistry.azurecr.io/myapp:1.0
      ports:
        - containerPort: 8080

---
# Example 6: Combined approach (Multiple ways in one pod)
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-mixed-secrets
  namespace: default
spec:
  containers:
    - name: app-container
      image: myapp:1.0
      ports:
        - containerPort: 8080
      # Method 1: Specific environment variables from secret
      env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: name
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password
        - name: LOG_LEVEL
          value: "INFO"
      # Method 2: Volume mount for other purposes
      volumeMounts:
        - name: secret-files
          mountPath: /app/secrets
          readOnly: true
  volumes:
    - name: secret-files
      secret:
        secretName: app-secret
        defaultMode: 0400
