# Method 1: Inject all secret key-value pairs as environment variables
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-secrets
spec:
  containers:
    - name: myapp
      image: ubuntu
      envFrom:
        - secretRef:
            name: app-secret

---
# Method 2: Inject specific secret keys as environment variables
apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-specific-secrets
spec:
  containers:
    - name: myapp
      image: ubuntu
      env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: name
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: password

---
# Method 3: Mount secrets as volume (files in container)
apiVersion: v1
kind: Pod
metadata:
  name: myapp-with-secret-volume
spec:
  containers:
    - name: myapp
      image: ubuntu
      volumeMounts:
        - name: secrets
          mountPath: /etc/secrets
          readOnly: true
  volumes:
    - name: secrets
      secret:
        secretName: app-secret
