# apiVersion: v1
# kind: Pod
# metadata:
#   name: sample
#   labels:
#     app: sample
# securityContexts:
#   runAsUser: 1000
# spec:
#   containers:
#   - name: sample
#     image: sample
#     ports:
#     - containerPort: 8080
#     securityContexts:
#       runAsUser: 1003

apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
  labels:
    app: security-demo
spec:
  # 🔐 Pod Level Security Context
  securityContext:
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 2000
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

  volumes:
  - name: shared-data
    emptyDir: {}

  containers:

  # ✅ Main Secure Container
  - name: secure-container
    image: nginx
    ports:
    - containerPort: 80

    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
        add:
          - NET_BIND_SERVICE

    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html

    resources:
      requests:
        cpu: "200m"
        memory: "256Mi"
      limits:
        cpu: "400m"
        memory: "512Mi"

  # ⚠️ Privileged Container Example (Not recommended in prod)
  - name: privileged-container
    image: busybox
    command: ["sh", "-c", "sleep 3600"]

    securityContext:
      privileged: true
      runAsUser: 0