apiVersion: v1
kind: Service
metadata:
  name: myappservice
  labels:
    app: myapp
  namespace: dev
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 90
      nodePort: 30008
  selector:
    app: myapp
