apiVersion: v1
kind: Pod
metadata:
  name: resource-demo-pod
  labels:
    app: resource-demo
spec:
  restartPolicy: Always

  # Init Container (runs before main container)
  initContainers:
  - name: init-container
    image: busybox
    command: ["sh", "-c", "echo Initializing... && sleep 10"]
    resources:
      requests:
        cpu: "100m"
        memory: "64Mi"
      limits:
        cpu: "200m"
        memory: "128Mi"

  containers:
  # Main Application Container
  - name: main-app
    image: nginx
    ports:
    - containerPort: 80

    resources:
      requests:
        cpu: "250m"
        memory: "256Mi"
        ephemeral-storage: "500Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"
        ephemeral-storage: "1Gi"

    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: empty-volume

  # Sidecar Container
  - name: sidecar-logger
    image: busybox
    command: ["sh", "-c", "while true; do echo logging; sleep 5; done"]

    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "300m"
        memory: "256Mi"

  # GPU Container Example (if cluster supports GPU)
  - name: gpu-app
    image: nvidia/cuda:11.0-base
    command: ["nvidia-smi"]

    resources:
      limits:
        nvidia.com/gpu: 1

  volumes:
  - name: empty-volume
    emptyDir: {}