apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
    type: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app:  myapp
  template:
    metadata:
        name: nginx
        labels:
          app: myapp
          type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx
    